# Generated by Django 5.0.6 on 2024-09-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_product_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
    ]
