# Generated by Django 5.0.6 on 2024-09-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_alter_product_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/'),
        ),
    ]
