# Generated by Django 5.0.6 on 2024-09-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0007_product_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
